
sudo: false

language: cpp

env:
  - ExternalData_OBJECT_STORES=${HOME}/.ExternalData

cache:
  directories:
    - ${ExternalData_OBJECT_STORES}

before_install:
  - brew update
  - brew install ninja $( command -V cmake &>2 /dev/null || echo "cmake" )

os:
  - osx

matrix:
  include:
    - osx_image: xcode8
    - osx_image: xcode7.3
    - osx_image: xcode7.2
    - osx_image: xcode7.1
    - osx_image: xcode7.0
    - osx_image: xcode6.4

before_script:
  - cmake --version

script:
  - cd .. && mkdir -p build && cd build
  - cmake -G Ninja  ../ITK
  - ninja ITKCommon1TestDriver
